Resources:
  ArtTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Art
      AttributeDefinitions:
        - AttributeName: "artId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "artId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"