Resources:
  StorageUnitTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: StorageUnit
      AttributeDefinitions:
        - AttributeName: "unitId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "unitId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST